name: NS2d
file: train_temporal.py

model: AFNO
dataset: ns2d
use_writer: True
res: 128
modes: 20
width: 32
lr: 0.001
lr_method: step
step_size: 100
step_gamma: 0.5
epochs: 500
noise_scale: 0.0
T_ar: 1
use_ln: 1
normalize: 0
T_bundle: 1
grad_clip: 10000.0

#resume_path: '/root/files/pdessl/logs_pretrain/AFNO_ns2d_1218_17_20_14:S_12_114400/model_99.pth'


# PDB 1, 1e-1, 1e-1
train_paths: [
  'ns2d_fno_1e-5',
  'ns2d_fno_1e-4',
  'ns2d_fno_1e-3',
  'ns2d_pdb_M1_eta1e-1_zeta1e-1',
  'ns2d_pdb_M1_eta1e-2_zeta1e-2',
  'ns2d_pdb_M1e-1_eta1e-1_zeta1e-1',
  'ns2d_pdb_M1e-1_eta1e-2_zeta1e-2',
  'swe_pdb',
  'dr_pdb',
  'ns2d_pda',
  'ns2d_cond_pda',
  'cfdbench'
]
test_paths: [
  'ns2d_fno_1e-5',
  'ns2d_fno_1e-4',
  'ns2d_fno_1e-3',
  'ns2d_pdb_M1_eta1e-1_zeta1e-1',
  'ns2d_pdb_M1_eta1e-2_zeta1e-2',
  'ns2d_pdb_M1e-1_eta1e-1_zeta1e-1',
  'ns2d_pdb_M1e-1_eta1e-2_zeta1e-2',
  'swe_pdb',
  'dr_pdb',
  'ns2d_pda',
  'ns2d_cond_pda',
  'cfdbench'
]
ntrain_list: [1000,8000,1000,9000,9000,9000,9000,900,900,6500,3100,9000]
data_weights: [8,2,8,1,1,1,1,8,8,1,3,1]
## AFNO for multiple PDE datasets pretraining
opt: adam
comment: 'mlp4t'
tasks:
  res: [128]
  normalize: [0]
  patch_size: [8]
  noise_scale: [0.0005]
  modes: [32]
  width: [512]
  mlp_ratio: [1]
  n_blocks: [4]
  n_layers: [4]
  lr: [0.001]
  epochs: [1000]
  lr_method: [cycle]
  warmup_epochs: [200]
  T_ar: [1]
  T_bundle: [1]
  beta1: [0.9]
  beta2: [0.9]
  batch_size: [32]
